---

- name: Install EPEL repository
  ansible.builtin.yum:
    name: epel-release
    state: installed

- name: Install other packages
  ansible.builtin.yum:
    name:
      - tmux
      - net-tools
      - perf
      - btop
      - mtr
      - bash-completion
      - sysstat
