- name: Deploy Consul servers
  hosts: consulservers
  strategy: linear
  become: yes
  gather_facts: no
  tasks:
    - import_tasks: tasks/fi_deploy_cs.yml

- name: Deploy Patroni with Consul agents
  hosts: patroniservers
  strategy: linear
  become: yes
  gather_facts: no
  tasks:
    - import_tasks: tasks/deploy_cs-agent.yml
    - import_tasks: tasks/deploy_patroni.yml
