galaxy_info:
  author: Hüseyin Sönmez
  description: This role is for installing some tools and configurations to first opened instances.
  license: Apache-2.0

  min_ansible_version: '2.12'

  platforms:
    - name: EL
      versions:
        - '9'

  galaxy_tags: []

dependencies: []
