---

- name: Installing PostgreSQL YUM repository [RHEL]
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: installed

- name: Install packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - postgresql14-server
    - postgresql14-contrib
    - pg_stat_kcache_14
    - pg_wait_sampling_14
    - timescaledb_14


- name: get consul bootstrap key from localhost

- name: copy consul patroni policy

- name: create patroni policy

- name: create token from patroni policy

- name: render patroni config
  with_items:
    - token from policy
    - ip from privateip
    - shared_preload_library for pgwatch2 prewarm timescaledb
    - hba add patroni nodes, load balancer ip
    - archive_command /bin/true

- name: start patroni

- name: create extension if not exists with patronictl master if current node is master

- name: print pretty patroni list

