- name: Deploy Consul servers
  hosts: consulservers
  strategy: linear
  become: true
  gather_facts: false
  roles:
    - fi_consul_servers


- name: Deploy Patroni with Consul agents
  hosts: patroniservers
  strategy: linear
  become: true
  gather_facts: false
  roles:
    - deploy_consul_client
    - deploy_patroni
