---

- name: install epel-release
  yum:
    name: epel-release
    state: installed

- name: install other packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - tmux
    - net-tools
    - perf
    - btop
    - mtr
    - bash-completion
    - sysstat
